### ISSUE TITLE
Example iOS ping test code compile errors

### ISSUE THREAD

**Issue by raygardener** [heroiclabs/heroiclabs-sdk-ios#19]
The HL website has an iOS ping example code snippet. But the line 

    `[HLClient.Ping].then(^(HLPing* pingInfo) {`

should read

    `[HLClient ping].then(^(HLPing* pingInfo) {`

Might also be worth mentioning that `catch` is a C++ keyword so the code doesn't compile in .mm files and to use `catchOn` instead.

**Comment by mofirouz** [comment]
@raygardener thanks for the notes. I'll go through and update the documentation now.

**Comment by raygardener** [comment]
Took a look; It's fixed in the "Anonymous Login" section but not in the "Connect with the API" section.
