### ISSUE TITLE
SDK error with Swift

### ISSUE THREAD

**Issue by schenkty** [heroiclabs/heroiclabs-sdk-ios#20]
I know swift is not supported but when i try to use the SDK i get his error and I wanted to know if there is something I can do to fix this issue. 

`func writeHeroicObject(key: String, value: String, table: String) {

    let data: [String : String] = [key : value]
    let key: String = key
    let table: String = table

    HLSessionClient.datastorePutData(data, withKey: key, inTable: table).catch({(_ error: Error) -> Void in
        print("The request failed with \(error.localizedDescription)")
    })
}`

Xcode throws an error "Ambiguous reference to member 'datastorePutData(_:withKey:inTable:)'" with the error details stating "Found this candidate (HeroicLabs.HLSessionClient)" four times. 

Are there default values that are fighting this or is there something I can fix. Any help would be great. Thanks

**Comment by mofirouz** [comment]
Hi Ty,

This is a problem in your code. You need an instance of the `HLSessionClient` object. The method `datastorePutData` is an instance method and not a static method.

I mentioned when we last spoke but we’ve not tested Swift support and don’t plan any official support until it becomes more stable. Also, keep an eye out for the huge platform update we’ve scheduled for release next week.

Cheers
